#!/bin/bash
## Author:	Owen Cocjin
## Version:	1.0
## Date:	05/03/20
## Title:	resetWifi
## Description: Reset wifi NIC
## Notes:

resetWifi(){
  sudo ip link set dev wlp2s0 down
  for i in {0..4}; do
    echo -n '.'
    sleep 1
  done
  sudo ip link set dev wlp2s0 up
  for i in {0..2}; do
    echo -n '.'
    sleep 1
  done
  ip addr show wlp2s0
}
