#!/bin/bash
## Author:	Owen Cocjin
## Version:	1.1
## Date:	05/03/20
## Title:	sources
## Description: Sources all functions
## Notes:
##	- Fix relative path

#Change p's value to the bashTools directory
p="/usr/local/bin"
for tool in $(ls ${p}/bashTools/Tools); do
	. ${p}/bashTools/Tools/${tool}
done
