#!/bin/bash
## Author:	Owen Cocjin
## Version:	1.0
## Date:	05/03/20
## Title:	sources
## Description: Sources all functions
## Notes:
. ./bashTools/cl
. ./bashTools/fillSpaces
. ./bashTools/n
. ./bashTools/resetWifi
. ./bashTools/stickynotes
. ./bashTools/wttr
