#!/bin/bash
## Author:	Owen Cocjin
## Version:	1.1
## Date:	05/03/20
## Title:	sources
## Description: Sources all functions
## Notes:
##	- Fix relative path

#Change p's value to the bashTools directory
p="/usr/local/bin"
. $p/bashTools/cl
. $p/bashTools/fillSpaces
. $p/bashTools/n
. $p/bashTools/resetWifi
. $p/bashTools/stickynotes
. $p/bashTools/wttr
