#!/bin/bash
## Author:	Owen Cocjin
## Version:	2.5
## Date:	10/12/20
## Title:	cl
## Description: List directories after moving into them
## Notes:
##    - Removed previous command success check

_base_cl(){
	#cd into directory
	if [[ -z "$*" ]]; then
		cd ~
	else
		cd "$*"
	fi
}

cl(){
	_base_cl "$*"
	ls --color=yes "$PWD"
}

cll(){
	#Like 'cl', but lists long format
	_base_cl "$*"
	ls -lh --color=yes "$PWD"
}

cla(){
	#Like 'cl', but lists all
	_base_cl "$*"
	ls -A --color=yes "$PWD"
}
