#!/bin/bash
## Author:  Owen Cocjin
## Version: 1.2
## Date:    2021.07.05
## Description: Run a command on a loop
## Notes:
## Update:
##  - No longer closes entire shell when invalid command passed
monloop(){
	if [[ -z ${1} ]]; then
		echo '[|X]: Missing command!'
		return 1
	fi
	if [[ -z ${2} ]]; then
		delay=0.5
	else
		delay=${2}
	fi

	if [[ ${delay} == 'x' ]];then
		while :; do
			clear
			eval ${1}
			read menu
		done
	else
		while :; do
			clear
			eval ${1}
			sleep ${delay}
		done
	fi
}
