#!/bin/bash
## Author:  Owen Cocjin
## Version: 0.1
## Date:    2021.04.08
## Description: Run a command on a loop
monloop(){
	if [[ -z ${1} ]]; then
		echo 'Missing command!'
		exit 1
	fi

	while :; do
		clear
		eval ${1}
		sleep 0.5
	done
}
