#!/bin/bash
## Author:  Owen Cocjin
## Version: 1.0
## Date:    2021.04.19
## Description: Run a command on a loop
## Notes:
## Update:
##    - Added ability to control delay time by passing a second arg
monloop(){
	if [[ -z ${1} ]]; then
		echo 'Missing command!'
		exit 1
	fi
	if [[ -z ${2} ]]; then
		delay=0.5
	else
		delay=${2}
	fi

	while :; do
		clear
		eval ${1}
		sleep ${delay}
	done
}
