#!/bin/bash
## Author:  Owen Cocjin
## Version: 1.4.1
## Date:    2022.10.25
## Title:   n
## Description: Send a command to background, silence it, disown it
## Updates:
##    - Added UID ext to end of nList file due to writing conflicts
##    - Fixed "egrep is deprecated" messages
## Notes:
##    - Added new SubFunctions path
n(){
	temp_list="/tmp/nList.${UID}"  #Set t
	if [[ ! -f ${temp_list} ]]; then touch ${temp_list}; chmod 666 ${temp_list}; fi
  # Process command
  if [[ $1 == '-l' ]]; then
	IFS=$'\n'  # Set internal field separator
	echo -e "\e[4mDATE (dd/mm/yy)\t\tPID\tCOMMAND\e[0m\n"
	if [[ ! -f ${temp_list} ]]; then return; fi;

	# If a n'd process is actually running, print it
	for i in $(cat ${temp_list}); do
		if [[ $(ps aux | awk '{print $2}' | grep -E $(cut -f2 <<< $i) | wc -l ) == '1' ]]; then
			echo "$i"
		fi
	done
  elif [[ $1 == '-c' ]]; then
    rm ${temp_list}
  elif [[ $1 == '-k' ]]; then
    sudo kill $2
  elif [[ $1 == '-s' ]]; then
    ps aux | grep $2 | grep -v 'grep'
  elif [[ $1 == '-h' ]]; then
    _help.n
  else
    echo "Silencing & disassociating $1..."
    $@ &>/dev/null & disown
    echo -e "$(date  +'%d/%m/%y - %H:%M:%S')\t$!\t$@" >> ${temp_list}
  fi
}
