#!/bin/bash
## Author:  Owen Cocjin
## Version: 1.1.1
## Date:    2022.02.26
## Description: Reads all lines that don't start with \n or #
## Notes:
##  - If the user doesn't have permissions to read the file, it will ask for sudo
## Update:
##  - Added a helper function to read the line
##    I thought the helper function would have to be longer hahaha
readconfig(){
	IFS=''
	if [[ ${1} == '' ]]; then
		echo '[|X]: Missing file name!'
		return 1
	elif [[ ! -f ${1} ]]; then
		echo '[|X]: File does not exist!'
		return 1
	fi
	#Check for read permission through head
	if [[ $(head -n 1 ${1} &>/dev/null; echo $?) != '0' ]]; then
		sudo cat ${1} | while read -r line; do
			_regexLine.readconfig "${line}"
		done
		# sudo egrep '^(?!#).*' ${1}
	else
		cat ${1} | while read -r line; do
			_regexLine.readconfig "${line}"
		done
		# egrep '^(?!\s*#).*' ${1}
	fi
}
