#!/bin/bash
## Author:	Owen Cocjin
## Version:	1.1
## Date:	2021.04.08
## Title:	resetWifi
## Description: Reset wifi NIC
## Notes:

resetwifi(){
  sudo ip link set dev wlp2s0 down
  for i in {0..4}; do
    echo -n '.'
    sleep 1
  done
  sudo ip link set dev wlp2s0 up
  for i in {0..2}; do
    echo -n '.'
    sleep 1
  done
  ip addr show wlp2s0
}
