#!/bin/bash
## Author:	Owen Cocjin
## Version:	1.2
## Date:    24/02/2021
## Title:   webnotes
## Description: Opens a notepad in firefox
## Notes:
## Update:
##    - Uses current directory for title if none specified

webnotes(){
	if [[ ! -z ${1} ]]; then
		notestitle=${1}
	else
		notestitle=$(pwd)
	fi
	firefox "data:text/html,<html><head><title>${notestitle}</title><style>p{font-size:25px;border:1px solid black;padding:10px;}</style></head><body><h1>Notes:</h1><p contenteditable='true';></p></br></body></html>"
}
